[tool.poetry]
name = "asset_management"
version = "1.0.0"
description = "Code for analysing both personal and company asseets"
authors = ["Jussi Virtanen <jussivirtanen1@outlook.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^1.5.1"
numpy = "^1.23.5"
yfinance = "^0.1.87"
SQLAlchemy = "^1.4.44"
DateTime = "^4.7"
matplotlib = "^3.6.2"
psycopg2 = "^2.9.5"
scikit-learn = "^1.2.1"
tensorflow = "^2.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
